server:
  port: 8888
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        native:
          searchLocations: file:///Users/yunus/IdeaProjects/MovieMicroserviceApp/confsvr/src/main/resources/config/licensingservice
        git:
          uri: https://github.com/Yunukas/config-repo
          searchPaths: userservice, ratingservice, movieservice