server:
  port: 8888
spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Yunukas/config-repo
          searchPaths: userservice, ratingservice, movieservice, appservice